// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by builder.sce : Please, do not edit this file
// ----------------------------------------------------------------------------
//
libPoint_Cloud_Tool_path = get_absolute_file_path('loader.sce');
//
// ulink previous function with same name
[bOK, ilib] = c_link('libPoint_Cloud_Toolbox');
if bOK then
  ulink(ilib);
end
//
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_common' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_ml' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_octree' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_io_ply' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_io' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_stereo' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_kdtree' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_search' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_sample_consensus' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_filters' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_features' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_registration' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_recognition' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_surface' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_tracking' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_keypoints' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_visualization' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_outofcore' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_segmentation' + getdynlibext());
link('/home/sh105/Documents/SH105_MILESTONE5/SH105_TOOLBOX/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libpcl_people' + getdynlibext());
list_functions = [ 'PointCloud';
];
addinter(libPoint_Cloud_Tool_path + filesep() + 'libPoint_Cloud_Toolbox' + getdynlibext(), 'libPoint_Cloud_Toolbox', list_functions);
// remove temp. variables on stack
clear libPoint_Cloud_Tool_path;
clear bOK;
clear ilib;
clear list_functions;
// ----------------------------------------------------------------------------
